#!/usr/bin/env bash
# Displays "Best School" 10 times
# Display 'Best School' and then 'Hi' on a new line for the 9th time.

index=o

while [ $index -lt 10 ]
do
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best School"
		(( index++ ))
done
